// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcQnVE1s_WUSp0tYf5VFpzCBAX4mfzV0',
    appId: '1:1044174461265:web:a2aa53b856602fa1811b70',
    messagingSenderId: '1044174461265',
    projectId: 'notesapp-1-0-0',
    authDomain: 'notesapp-1-0-0.firebaseapp.com',
    storageBucket: 'notesapp-1-0-0.appspot.com',
    measurementId: 'G-95TNWZHPR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRY79ymmtEInfknf_8wOqsZGpFqJIZkk',
    appId: '1:1044174461265:android:2be80fc758aa88d5811b70',
    messagingSenderId: '1044174461265',
    projectId: 'notesapp-1-0-0',
    storageBucket: 'notesapp-1-0-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOlYXAl90R4Ovq9YVySQBvfabsdPj0a5Y',
    appId: '1:1044174461265:ios:2b7b627cb796785d811b70',
    messagingSenderId: '1044174461265',
    projectId: 'notesapp-1-0-0',
    storageBucket: 'notesapp-1-0-0.appspot.com',
    iosClientId: '1044174461265-7r5rs6e4ulv0notuq28csld6g1ng4p1e.apps.googleusercontent.com',
    iosBundleId: 'com.firstproject.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOlYXAl90R4Ovq9YVySQBvfabsdPj0a5Y',
    appId: '1:1044174461265:ios:57f4bed3fa4153bd811b70',
    messagingSenderId: '1044174461265',
    projectId: 'notesapp-1-0-0',
    storageBucket: 'notesapp-1-0-0.appspot.com',
    iosClientId: '1044174461265-89pfh6hton3ik3gnbtmi3lnnterlcsqq.apps.googleusercontent.com',
    iosBundleId: 'com.firstproject.notesapp.RunnerTests',
  );
}
